services:
  service:
    container_name: gateway_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:${PORT:-4000}
    networks:
      - auth-service_network

networks:
  auth-service_network:
    external: true
