export const MINIO_CLIENT = 'MINIO_CLIENT'
export const IMAGES_BUCKET = 'images'
export const AUTH_PACKAGE = 'AUTH_PACKAGE'
export const AUTH_PACKAGE_NAME = 'auth'
export const AUTH_SERVICE_NAME = 'AuthService'
export const IMAGE_QUEUE = 'image'
export const COMPRESS_JOB = 'compress'
